#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════════════════╗
║  STEP 01 — Download GDSC Drug Response Data (ERBB Family Expansion)         ║
╠══════════════════════════════════════════════════════════════════════════════╣
║                                                                              ║
║  PURPOSE:                                                                    ║
║    Download drug sensitivity (IC50) data from the Genomics of Drug           ║
║    Sensitivity in Cancer (GDSC) database. This is our PRIMARY source of      ║
║    ground-truth labels — it tells us which cell lines are SENSITIVE vs.       ║
║    RESISTANT to each drug.                                                   ║
║                                                                              ║
║  ERBB FAMILY EXPANSION (v2):                                                 ║
║    This script now supports BOTH EGFR-mutant NSCLC and HER2+ breast cancer.  ║
║    It uses gene-aware tissue filtering:                                       ║
║      • EGFR drugs (Osimertinib, Gefitinib, Afatinib, Erlotinib)             ║
║        → filtered to NSCLC cell lines (LUAD/LUSC)                            ║
║      • HER2 drugs (Lapatinib, Neratinib)                                    ║
║        → filtered to breast cancer cell lines (BRCA)                         ║
║    Each row gets a `target_protein` column (EGFR or ERBB2) based on the         ║
║    drug-gene mapping in config.yaml.                                         ║
║                                                                              ║
║  WHY GDSC?                                                                   ║
║    • Largest public pharmacogenomics dataset (>1000 cell lines, >400 drugs)  ║
║    • Contains dose-response curves for 6 ERBB-family TKIs                    ║
║    • Each cell line has known mutation profiles (EGFR/ERBB2 status)          ║
║    • IC50 values provide continuous resistance scores                        ║
║    • GDSC2 uses improved 5-point dose-response methodology                  ║
║                                                                              ║
║  NOTE (June 2025+):                                                          ║
║    GDSC data has migrated from cancerrxgene.org to the Sanger Cell Model     ║
║    Passports. Automatic download is no longer possible — files must be        ║
║    downloaded manually. This script guides you through the process and then   ║
║    processes the downloaded files.                                            ║
║                                                                              ║
║  WHAT WE NEED:                                                               ║
║    1. Drug Sensitivity Data  → GDSC2 fitted dose-response (IC50/AUC)        ║
║    2. Model Annotation       → cell line metadata (tissue type, COSMIC ID)   ║
║                                                                              ║
║  INPUT FILES  (data/raw/gdsc/ — manually downloaded):                        ║
║    GDSC2_fitted_dose_response_*.xlsx   (GDSC2 IC50 dataset)                 ║
║    model_list_*.csv                     (cell line annotation)               ║
║                                                                              ║
║  OUTPUT FILES (data/processed/gdsc/ — generated by this script):             ║
║    gdsc_erbb_tki_responses.csv   (NSCLC + breast ERBB TKI responses)        ║
║                                                                              ║
║  DATA FLOW:                                                                  ║
║    Manual Download → Auto-detect format → Gene-aware tissue filtering →      ║
║    Extract IC50 → Assign target_protein → Save cleaned CSV                      ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""

import argparse
import sys
from pathlib import Path

import pandas as pd

# ── Project Root & Config (initialized by run()) ─────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
from src.ptm_bdl.config import load_config

# Module-level globals — set by run(case_study)
cfg = None
RAW_DIR = None
OUT_DIR = None


def _init(case_study: str):
    """Initialize module globals for a given case study."""
    global cfg, RAW_DIR, OUT_DIR
    cfg = load_config(case_study=case_study)
    RAW_DIR = PROJECT_ROOT / cfg["paths"]["raw_data"] / "gdsc"
    OUT_DIR = PROJECT_ROOT / cfg["paths"]["processed_data"] / "gdsc"
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"  [Config] case_study = {case_study}")

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1: Locate Downloaded Files (Manual Download Required)
# ══════════════════════════════════════════════════════════════════════════════

MANUAL_DOWNLOAD_INSTRUCTIONS = """
╔══════════════════════════════════════════════════════════════════════════════╗
║  MANUAL DOWNLOAD REQUIRED                                                    ║
║                                                                              ║
║  GDSC data has moved to Sanger Cell Model Passports.                        ║
║  Please follow these steps:                                                  ║
║                                                                              ║
║  1. Open: https://cellmodelpassports.sanger.ac.uk/downloads                 ║
║                                                                              ║
║  2. DRUG SENSITIVITY DATA (required — our IC50 labels):                     ║
║     → Scroll to "Functional Datasets" section                               ║
║     → Click "Drug Sensitivity Data"                                         ║
║     → Under "GDSC2 IC50 Data" (~21 MB), click "GDSC2 dataset"             ║
║       (provides IC50, AUC, and Z-Score values)                              ║
║     → Move/rename the downloaded file to:                                    ║
║       {raw_dir}/gdsc2_dose_response.xlsx                                     ║
║       (or just drop it in the folder — any filename with "gdsc2" works)     ║
║                                                                              ║
║  3. MODEL ANNOTATION (recommended — cell line metadata):                    ║
║     → Click "Model Annotation" in "Model & Gene Annotation" section         ║
║     → Under "Model List" (~934 kB), click "list of all annotated models"   ║
║       (tissue type, cancer type, COSMIC IDs, identifiers)                   ║
║     → Move/rename the downloaded file to:                                    ║
║       {raw_dir}/model_list.csv                                               ║
║       (or just drop it in the folder — any filename with "model_list" works)║
║                                                                              ║
║  4. Re-run this script after placing the files.                             ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""


def find_file(directory: Path, patterns: list[str], description: str) -> Path | None:
    """
    Search for a file matching any of the given patterns (case-insensitive).
    Supports .xlsx, .csv, and .tsv extensions.
    
    Returns the first matching file path, or None if not found.
    """
    all_files = list(directory.iterdir()) if directory.exists() else []

    for f in sorted(all_files):
        fname_lower = f.name.lower()
        # Skip hidden files and temp files
        if fname_lower.startswith(".") or fname_lower.startswith("~"):
            continue
        # Check each pattern
        for pattern in patterns:
            if pattern.lower() in fname_lower:
                print(f"  ✓ Found {description}: {f.name}")
                return f

    return None


def locate_gdsc_files():
    """
    Look for manually downloaded GDSC files in the raw/gdsc/ directory.
    
    We search for files by name patterns since the exact filename depends
    on when the user downloaded from Cell Model Passports (they append dates,
    change formats between releases, etc.).
    
    Returns (dose_response_path, cell_lines_path) — either may be None.
    """
    print("\n" + "=" * 70)
    print("STEP 1.1: Locating GDSC Data Files")
    print("=" * 70)
    print(f"  Looking in: {RAW_DIR}")

    if RAW_DIR.exists():
        files_in_dir = [f.name for f in RAW_DIR.iterdir()
                        if not f.name.startswith(".")]
        print(f"  Files found: {files_in_dir}")
    else:
        print(f"  Directory does not exist yet. Creating...")
        RAW_DIR.mkdir(parents=True, exist_ok=True)

    # ── Search for dose-response file ──────────────────────────────────────
    dose_response_patterns = [
        "gdsc2_dose_response",
        "gdsc2_fitted_dose_response",
        "fitted_dose_response_gdsc2",
        "dose_response_gdsc2",
        "gdsc_dose_response",
        "gdsc2_ic50",
        "gdsc2-ic50",
        "gdsc2_dataset",
    ]
    dose_response_path = find_file(
        RAW_DIR, dose_response_patterns, "Dose-response data"
    )

    # ── Search for cell line details / model annotation file ───────────────
    cell_lines_patterns = [
        "cell_lines_details",
        "cell_line_details",
        "model_annotation",
        "model_list",
    ]
    cell_lines_path = find_file(
        RAW_DIR, cell_lines_patterns, "Cell line details / Model annotation"
    )

    # ── Report what's missing ──────────────────────────────────────────────
    missing = []
    if dose_response_path is None:
        missing.append("Drug Sensitivity Data (GDSC2 dose-response)")
    if cell_lines_path is None:
        missing.append("Model Annotation (cell line details)")

    if missing:
        print(f"\n  ✗ Missing {len(missing)} file(s):")
        for m in missing:
            print(f"    • {m}")
        print(MANUAL_DOWNLOAD_INSTRUCTIONS.format(raw_dir=RAW_DIR))

        if dose_response_path is None:
            return None, cell_lines_path

    return dose_response_path, cell_lines_path


def load_datafile(path: Path) -> pd.DataFrame:
    """
    Auto-detect file format and load as DataFrame.
    Supports .xlsx, .csv, .tsv
    """
    suffix = path.suffix.lower()
    print(f"  Loading {path.name} (format: {suffix})...")

    if suffix == ".xlsx" or suffix == ".xls":
        return pd.read_excel(path)
    elif suffix == ".tsv":
        return pd.read_csv(path, sep="\t")
    else:  # default to CSV
        return pd.read_csv(path)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2: Filter and Process GDSC Data (ERBB Family — Multi-Gene)
# ══════════════════════════════════════════════════════════════════════════════

COLUMN_ALIASES = {
    "COSMIC_ID": "COSMIC_ID",
    "COSMICID": "COSMIC_ID",
    "cosmic_id": "COSMIC_ID",
    "CELL_LINE_NAME": "CELL_LINE_NAME",
    "cell_line_name": "CELL_LINE_NAME",
    "Cell Line Name": "CELL_LINE_NAME",
    "SANGER_MODEL_ID": "SANGER_MODEL_ID",
    "sanger_model_id": "SANGER_MODEL_ID",
    "model_id": "SANGER_MODEL_ID",
    "TCGA_DESC": "TCGA_DESC",
    "tcga_desc": "TCGA_DESC",
    "TCGA_description": "TCGA_DESC",
    "tcga_classification": "TCGA_DESC",
    "CANCER_TYPE": "TCGA_DESC",
    "cancer_type": "TCGA_DESC",
    "tissue": "TCGA_DESC",
    "DRUG_ID": "DRUG_ID",
    "drug_id": "DRUG_ID",
    "Drug Id": "DRUG_ID",
    "DRUG_NAME": "DRUG_NAME",
    "drug_name": "DRUG_NAME",
    "Drug Name": "DRUG_NAME",
    "PUTATIVE_TARGET": "PUTATIVE_TARGET",
    "putative_target": "PUTATIVE_TARGET",
    "Target": "PUTATIVE_TARGET",
    "PATHWAY_NAME": "PATHWAY_NAME",
    "pathway_name": "PATHWAY_NAME",
    "Target Pathway": "PATHWAY_NAME",
    "LN_IC50": "LN_IC50",
    "ln_IC50": "LN_IC50",
    "ln_ic50": "LN_IC50",
    "IC50": "LN_IC50",
    "AUC": "AUC",
    "auc": "AUC",
    "RMSE": "RMSE",
    "rmse": "RMSE",
    "Z_SCORE": "Z_SCORE",
    "z_score": "Z_SCORE",
}


def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Rename columns to canonical names using the alias map."""
    rename_map = {}
    for col in df.columns:
        if col in COLUMN_ALIASES:
            canonical = COLUMN_ALIASES[col]
            if canonical not in rename_map.values():
                rename_map[col] = canonical

    if rename_map:
        print(f"  Column renames applied: { {k: v for k, v in rename_map.items() if k != v} }")
        df = df.rename(columns=rename_map)

    return df


def process_gdsc_data(dose_response_path: Path, cell_lines_path: Path | None):
    """
    Filter GDSC data to extract ERBB-family TKI responses for NSCLC and
    breast cancer cell lines.
    
    PROCESSING LOGIC (ERBB Family Expansion):
    ──────────────────────────────────────────
    1. Load the full GDSC2 dose-response dataset (~250K rows, all drugs + all lines)
    2. Filter to keep ONLY our 6 target ERBB-family TKI drugs:
       EGFR drugs:
         - Osimertinib (ID 1919): 3rd-gen, targets T790M
         - Gefitinib   (ID 1010): 1st-gen, reversible
         - Afatinib    (ID 1032): 2nd-gen, irreversible pan-ERBB
         - Erlotinib   (ID 1168): 1st-gen, reversible
       HER2 drugs:
         - Lapatinib   (ID 1558): dual EGFR/HER2, reversible
         - Neratinib   (ID 2097): pan-ERBB, irreversible
    3. Gene-aware tissue filtering:
       - EGFR drugs → keep only NSCLC cell lines (LUAD/LUSC)
       - HER2 drugs → keep only breast cancer cell lines (BRCA)
    4. Assign target_protein column based on drug-gene mapping
    5. Classify resistance: LN_IC50 ≥ 0 → resistant, < 0 → sensitive
    6. Output: gdsc_erbb_tki_responses.csv with target_protein column
    
    WHY GENE-AWARE FILTERING:
    ─────────────────────────
    - EGFR TKIs are clinically relevant in NSCLC (EGFR-mutant lung cancer)
    - HER2 TKIs are clinically relevant in breast cancer (HER2+ breast)
    - Afatinib targets both but is primarily used in NSCLC context
    - Lapatinib/Neratinib target both but are primarily used in breast context
    - This gene-aware approach ensures biological coherence
    """
    print("\n" + "=" * 70)
    print("STEP 1.2: Processing GDSC Data (ERBB Family)")
    print("=" * 70)

    # ── Load dose-response data ──────────────────────────────────────────────
    if dose_response_path is None or not dose_response_path.exists():
        print("  ✗ Dose-response file not found. Cannot proceed.")
        print("  → Follow the manual download instructions above.")
        return None

    df_response = load_datafile(dose_response_path)
    df_response = normalize_columns(df_response)
    print(f"  → Total records: {len(df_response):,}")
    print(f"  → Columns: {list(df_response.columns)}")

    # ── Validate required columns exist ───────────────────────────────────────
    required_cols = ["DRUG_ID", "LN_IC50"]
    missing_cols = [c for c in required_cols if c not in df_response.columns]
    if missing_cols:
        print(f"\n  ⚠ Missing expected columns: {missing_cols}")
        print(f"  Available columns: {list(df_response.columns)}")
        print("  The file format may have changed. Please check the downloaded file.")
        drug_cols = [c for c in df_response.columns
                     if "drug" in c.lower() or "ic50" in c.lower() or "auc" in c.lower()]
        if drug_cols:
            print(f"  Possible drug-related columns found: {drug_cols}")
        return None

    # ── Filter for our target ERBB-family TKI drugs ───────────────────────────
    target_drug_ids = list(cfg["gdsc"]["drug_ids"].values())
    target_drug_names = list(cfg["gdsc"]["drug_ids"].keys())
    # drug_gene_map values are lists (e.g., ["EGFR", "ERBB2"])
    drug_gene_map = cfg["gdsc"]["drug_protein_mapping"]
    tissue_filters = cfg["project"]["tissue_filters"]

    print(f"\n  Filtering for ERBB-family TKI drugs: {target_drug_names}")
    print(f"  Expected Drug IDs: {target_drug_ids}")
    print(f"  Drug-gene mapping: {drug_gene_map}")

    # Primary filter: by drug NAME (case-insensitive)
    if "DRUG_NAME" in df_response.columns:
        name_mask = df_response["DRUG_NAME"].str.lower().isin(
            [n.lower() for n in target_drug_names]
        )
        df_tki = df_response[name_mask].copy()
        print(f"  → Records matched by DRUG_NAME: {len(df_tki):,}")

        # Verify: show actual drug IDs found vs. expected
        actual_ids = df_tki[["DRUG_ID", "DRUG_NAME"]].drop_duplicates()
        for _, row in actual_ids.iterrows():
            expected_id = cfg["gdsc"]["drug_ids"].get(row["DRUG_NAME"], "?")
            match_str = "✓" if row["DRUG_ID"] == expected_id else f"⚠ config says {expected_id}"
            gene = drug_gene_map.get(row["DRUG_NAME"], "?")
            print(f"    {row['DRUG_NAME']}: ID {row['DRUG_ID']} {match_str} → {gene}")
    else:
        # Fallback: filter by drug ID only
        df_tki = df_response[df_response["DRUG_ID"].isin(target_drug_ids)].copy()
        print(f"  → Records matched by DRUG_ID: {len(df_tki):,}")

    if len(df_tki) == 0:
        print("\n  ⚠ No records found for our target drugs!")
        if "DRUG_NAME" in df_response.columns:
            all_names = sorted(df_response["DRUG_NAME"].unique())
            erbb_drugs = [d for d in all_names
                          if any(x in str(d).lower()
                                 for x in ["osimertinib", "gefitinib", "afatinib",
                                           "erlotinib", "lapatinib", "neratinib",
                                           "azd9291"])]
            print(f"  ERBB-related drugs in file: {erbb_drugs}")
        return None

    # ── Show per-drug counts BEFORE tissue filtering ─────────────────────────
    print("\n  Per-drug cell line counts (BEFORE tissue filtering):")
    for drug_name in target_drug_names:
        drug_subset = df_tki[df_tki["DRUG_NAME"].str.lower() == drug_name.lower()]
        if "CELL_LINE_NAME" in df_tki.columns:
            n_lines = drug_subset["CELL_LINE_NAME"].nunique()
        else:
            n_lines = len(drug_subset)
        actual_id = drug_subset["DRUG_ID"].iloc[0] if len(drug_subset) > 0 else "N/A"
        print(f"    {drug_name} (ID {actual_id}): {n_lines} cell lines tested")

    # ══════════════════════════════════════════════════════════════════════════
    # GENE-AWARE TISSUE FILTERING
    # For each drug, apply the tissue filter corresponding to its target gene.
    # EGFR drugs → NSCLC, HER2 drugs → breast cancer
    # ══════════════════════════════════════════════════════════════════════════

    if "TCGA_DESC" not in df_tki.columns:
        print("\n  ⚠ No TCGA_DESC column found — cannot apply tissue filtering.")
        print("    Proceeding with all cell lines (manual review recommended).")
        df_filtered = df_tki.copy()
        df_filtered["target_protein"] = df_filtered["DRUG_NAME"].map(
            lambda d: drug_gene_map.get(d, "EGFR")
        )
    else:
        print("\n  Applying gene-aware tissue filtering...")
        print("  (Drugs mapped to multiple genes create separate rows per tissue context)")
        filtered_parts = []

        for drug_name in target_drug_names:
            # drug_gene_map values are lists, e.g. ["EGFR", "ERBB2"]
            genes = drug_gene_map.get(drug_name, ["EGFR"])
            if isinstance(genes, str):
                genes = [genes]  # backward compat: convert string to list

            drug_mask = df_tki["DRUG_NAME"].str.lower() == drug_name.lower()
            drug_subset = df_tki[drug_mask].copy()

            if len(drug_subset) == 0:
                print(f"    {drug_name} ({genes}): no records found in GDSC, skipping")
                continue

            # For each gene context, apply the corresponding tissue filter
            for gene in genes:
                tissue_regex = tissue_filters.get(gene, "")

                if tissue_regex:
                    tissue_mask = drug_subset["TCGA_DESC"].str.contains(
                        tissue_regex, case=False, na=False
                    )
                    drug_tissue = drug_subset[tissue_mask].copy()
                else:
                    drug_tissue = drug_subset.copy()

                drug_tissue["target_protein"] = gene

                n_total = len(drug_subset)
                n_kept = len(drug_tissue)
                n_lines = drug_tissue["CELL_LINE_NAME"].nunique() if "CELL_LINE_NAME" in drug_tissue.columns else n_kept
                print(
                    f"    {drug_name} ({gene}): {n_total} total → {n_kept} after '{tissue_regex}' filter ({n_lines} cell lines)")

                if n_kept > 0:
                    filtered_parts.append(drug_tissue)

        if not filtered_parts:
            print("\n  ⚠ No records remaining after tissue filtering!")
            return None

        df_filtered = pd.concat(filtered_parts, ignore_index=True)

    print(f"\n  → Total ERBB TKI records after tissue filtering: {len(df_filtered):,}")
    if "CELL_LINE_NAME" in df_filtered.columns:
        print(f"  → Unique cell lines: {df_filtered['CELL_LINE_NAME'].nunique()}")

    if len(df_filtered) == 0:
        print("\n  ⚠ No cell lines found after filtering!")
        return None

    # ── Extract and clean key columns ────────────────────────────────────────
    columns_to_keep = [
        "COSMIC_ID", "CELL_LINE_NAME", "SANGER_MODEL_ID",
        "TCGA_DESC", "DRUG_ID", "DRUG_NAME",
        "PUTATIVE_TARGET", "PATHWAY_NAME",
        "LN_IC50", "AUC", "RMSE", "Z_SCORE",
        "target_protein"
    ]

    available_cols = [c for c in columns_to_keep if c in df_filtered.columns]
    df_clean = df_filtered[available_cols].copy()

    # ── Add resistance classification ────────────────────────────────────────
    # Use LN_IC50 ≥ 0 (IC50 ≥ 1 µM) as the absolute pharmacological threshold.
    print("\n  Classifying resistance status (LN_IC50 ≥ 0 → resistant)...")
    df_clean["resistance_label"] = 0  # 0 = sensitive, 1 = resistant
    df_clean.loc[df_clean["LN_IC50"] >= 0, "resistance_label"] = 1

    # ── Per-gene, per-drug summary ────────────────────────────────────────────
    for gene in df_clean["target_protein"].unique():
        gene_mask = df_clean["target_protein"] == gene
        gene_df = df_clean[gene_mask]
        print(f"\n  {gene} drugs:")
        for drug_name in gene_df["DRUG_NAME"].unique():
            drug_mask = gene_df["DRUG_NAME"].str.lower() == drug_name.lower()
            n_s = (drug_mask & (gene_df["resistance_label"] == 0)).sum()
            n_r = (drug_mask & (gene_df["resistance_label"] == 1)).sum()
            n_total = n_s + n_r
            pct_s = 100 * n_s / n_total if n_total > 0 else 0
            print(f"    {drug_name}: Sensitive={n_s} ({pct_s:.1f}%), Resistant={n_r}")

    # ── Save processed data (case-study-specific) ─────────────────────────────
    case_study_name = cfg.get("case_study", "egfr_erbb2_tki")
    output_path = OUT_DIR / f"gdsc_{case_study_name}_responses.csv"
    df_clean.to_csv(output_path, index=False)
    print(f"\n  ✓ Saved GDSC responses: {output_path}")
    print(f"    Total records: {len(df_clean):,}")

    # ── Print summary statistics ─────────────────────────────────────────────
    print("\n" + "-" * 60)
    print("SUMMARY OF GDSC DATA (ERBB FAMILY)")
    print("-" * 60)
    print(f"  Total dose-response records (all drugs, all tissues): {len(df_response):,}")
    print(f"  ERBB-family TKI records (filtered): {len(df_clean):,}")

    for gene in sorted(df_clean["target_protein"].unique()):
        gene_df = df_clean[df_clean["target_protein"] == gene]
        n_lines = gene_df["CELL_LINE_NAME"].nunique() if "CELL_LINE_NAME" in gene_df.columns else "?"
        n_sensitive = (gene_df["resistance_label"] == 0).sum()
        n_resistant = (gene_df["resistance_label"] == 1).sum()
        pct_sens = 100 * n_sensitive / len(gene_df) if len(gene_df) > 0 else 0
        print(f"\n  {gene}:")
        print(f"    Records: {len(gene_df):,}")
        print(f"    Cell lines: {n_lines}")
        print(f"    Sensitive: {n_sensitive} ({pct_sens:.1f}%)")
        print(f"    Resistant: {n_resistant} ({100 - pct_sens:.1f}%)")
        print(f"    Drugs: {sorted(gene_df['DRUG_NAME'].unique())}")

    # Combined class balance
    total = len(df_clean)
    total_sens = (df_clean["resistance_label"] == 0).sum()
    print(f"\n  Combined class balance:")
    print(f"    Total: {total}, Sensitive: {total_sens} ({100 * total_sens / total:.1f}%), "
          f"Resistant: {total - total_sens} ({100 * (total - total_sens) / total:.1f}%)")

    # List notable cell lines
    if "CELL_LINE_NAME" in df_clean.columns:
        known_egfr_lines = [
            "HCC827", "H1975", "PC-9", "H1650", "H3255", "H820", "H1573"
        ]
        known_her2_lines = [
            "BT-474", "SKBR3", "AU565", "HCC1954", "MDA-MB-453",
            "MDA-MB-361", "ZR-75-30", "UACC-812"
        ]
        found_egfr = [l for l in known_egfr_lines if l in df_clean["CELL_LINE_NAME"].values]
        found_her2 = [l for l in known_her2_lines if l in df_clean["CELL_LINE_NAME"].values]
        print(f"\n  Known EGFR-mutant NSCLC lines found: {found_egfr}")
        print(f"  Known HER2+ breast cancer lines found: {found_her2}")

    return df_clean


# ══════════════════════════════════════════════════════════════════════════════
# MAIN EXECUTION
# ══════════════════════════════════════════════════════════════════════════════

def run(case_study: str = "egfr_erbb2_tki"):
    """Main entry point — call from thin wrappers or CLI."""
    _init(case_study)

    print("╔══════════════════════════════════════════════════════════════╗")
    print("║  STEP 01: Download & Process GDSC Drug Response Data       ║")
    print(f"║  Case study: {case_study:46s} ║")
    print("╚══════════════════════════════════════════════════════════════╝")

    dose_path, cell_path = locate_gdsc_files()

    if dose_path is not None:
        df_result = process_gdsc_data(dose_path, cell_path)
        if df_result is not None:
            print("\n✓ Step 01 complete! GDSC data ready for harmonization (Step 06).")
        else:
            print("\n✗ Step 01 incomplete. Check processing errors above.")
    else:
        print("\n✗ Step 01 incomplete. Please download the required files and re-run.")
        sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Step 01 — Download GDSC data")
    parser.add_argument("--case-study", default="egfr_erbb2_tki",
                        help="Case study name (default: egfr_erbb2_tki)")
    args, _ = parser.parse_known_args()
    run(case_study=args.case_study)
